global:
  scrape_interval:     15s
  scrape_timeout:      14s
  external_labels:
      hello_prometheus_version: '1.0'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'pg_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']