global:
  scrape_interval:     15s
  scrape_timeout:      14s
  evaluation_interval: 15s
  external_labels:
      hello_prometheus_version: '1.0'

rule_files:
  - alerting.extended.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'pg_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'pg_exporter_two'
    static_configs:
      - targets: ['postgres_exporter_two:9187']